2024-11-15 20:41:29,633 | MainProcess | MainThread | docker.utils.config | DEBUG | Trying paths: ['/Users/ctavolazzi/.docker/config.json', '/Users/ctavolazzi/.dockercfg']
2024-11-15 20:41:29,633 | MainProcess | MainThread | docker.utils.config | DEBUG | Found file at path: /Users/ctavolazzi/.docker/config.json
2024-11-15 20:41:29,634 | MainProcess | MainThread | docker.auth | DEBUG | Found 'credsStore' section
2024-11-15 20:41:29,666 | MainProcess | MainThread | urllib3.connectionpool | DEBUG | http://localhost:None "GET /version HTTP/1.1" 200 None
2024-11-15 20:41:29,681 | MainProcess | MainThread | urllib3.connectionpool | DEBUG | http://localhost:None "GET /v1.44/images/python:3-slim/json HTTP/1.1" 200 None
2024-11-15 20:41:29,771 | MainProcess | MainThread | urllib3.connectionpool | DEBUG | http://localhost:None "POST /v1.44/containers/create?name=autogen-code-exec-bc1bcfd8-acbd-47f8-ab3d-5d6441dae0a8 HTTP/1.1" 201 None
2024-11-15 20:41:29,794 | MainProcess | MainThread | urllib3.connectionpool | DEBUG | http://localhost:None "GET /v1.44/containers/b72abcb1855ff7cd98d2d70b1aa80edf85c1dc2e38439223b66bf1b3ac4558fb/json HTTP/1.1" 200 None
2024-11-15 20:41:30,585 | MainProcess | MainThread | urllib3.connectionpool | DEBUG | http://localhost:None "POST /v1.44/containers/b72abcb1855ff7cd98d2d70b1aa80edf85c1dc2e38439223b66bf1b3ac4558fb/start HTTP/1.1" 204 0
2024-11-15 20:41:30,739 | MainProcess | MainThread | urllib3.connectionpool | DEBUG | http://localhost:None "GET /v1.44/containers/b72abcb1855ff7cd98d2d70b1aa80edf85c1dc2e38439223b66bf1b3ac4558fb/json HTTP/1.1" 200 None
2024-11-15 20:41:30,741 | MainProcess | MainThread | __main__ | INFO | Setting up agents
2024-11-15 20:41:30,743 | MainProcess | MainThread | httpx | DEBUG | load_ssl_context verify=True cert=None trust_env=True http2=False
2024-11-15 20:41:30,744 | MainProcess | MainThread | httpx | DEBUG | load_verify_locations cafile='/Users/ctavolazzi/.pyenv/versions/3.10.13/lib/python3.10/site-packages/certifi/cacert.pem'
2024-11-15 20:41:30,786 | MainProcess | MainThread | __main__ | INFO | Starting Autogen CYOA game
2024-11-15 20:41:30,787 | MainProcess | MainThread | __main__ | ERROR | Game error: 'AutogenGame' object has no attribute 'get_current_scene'
2024-11-15 20:41:30,788 | MainProcess | MainThread | __main__ | INFO | Game ended
2024-11-15 20:41:30,939 | MainProcess | MainThread | urllib3.connectionpool | DEBUG | http://localhost:None "GET /v1.44/containers/autogen-code-exec-bc1bcfd8-acbd-47f8-ab3d-5d6441dae0a8/json HTTP/1.1" 200 None
2024-11-15 20:41:41,354 | MainProcess | MainThread | urllib3.connectionpool | DEBUG | http://localhost:None "POST /v1.44/containers/b72abcb1855ff7cd98d2d70b1aa80edf85c1dc2e38439223b66bf1b3ac4558fb/stop HTTP/1.1" 204 0
